name: Deployment Pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Setup
        id: setup
        run: |
          npm ci
          npm run test
  deploy-to-dev:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::952488780586:role/github-deploy-to-cloudformation-role
          aws-region: us-east-1
          run: |
            echo "This a pull request from the branch ${{ github.head_ref }}!"
            echo "Deploying to dev..."
            ls
            npx sst deploy --stage dev-${{ github.head_ref }}

  deploy-to-prod:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: DeployToProd
        id: prod
        run: |
          ls
          echo "This is Main!"
          echo "Deploying to production..."
