name: Deployment Pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Setup
        id: setup
        run: |
          npm ci
          npm run test
  deploy-to-dev:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: DeployToDev
        id: dev
        run: |
          echo "This a pull request from the branch ${{ github.head_ref }}!"
          echo "Deploying to dev..."

          cat > foo.conf << EOF
            [nft-tshirt-shop-dev]
            aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF

          cat ~/.aws/credentials
          AWS_PROFILE=nft-tshirt-shop-dev npx sst deploy --stage dev-${{ github.head_ref }}
  deploy-to-prod:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: DeployToProd
        id: prod
        run: |
          ls
          echo "This is Main!"
          echo "Deploying to production..."
