name: Deployment Pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Setup
        id: setup
        run: |
          npm ci
          npm run test
  deploy-to-dev:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: DeployToDev
        id: dev
        run: |
          echo "This is a pull request!"
          echo "Deploying to dev..."
          echo ${GITHUB_REF}
          AWS_PROFILE=nft-tshirt-shop-dev npx sst deploy --stage dev-${GITHUB_REF##*/}
  deploy-to-prod:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' }}
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: DeployToProd
        id: prod
        run: |
          ls
          echo "This is Main!"
          echo "Deploying to production..."
