name: Deployment Pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)!
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Prepare
        id: prep
        run: |
          ls
          echo "This is a pull request!"
          echo "Deploying to dev..."
  deploy-to-prod:
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)
    steps:
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Prepare
        id: prep
        run: |
          ls
          echo "This is Main!"
          echo "Deploying to production..."
