name: Deployment Pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !github.event.pull_request.draft
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::952488780586:role/github-deploy-to-cloudformation-role

      - name: Fetch Repo Code
        uses: actions/checkout@v2

      - name: Setup
        run: |
          npm ci
          npm run test
          cd ./frontend
          npm ci
          cd ..
          echo "Deploying to dev..."
          npx sst deploy --stage dev-${{ github.head_ref }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::738219726652:role/github-deploy-to-cloudformation-role

      - name: Fetch Repo Code
        uses: actions/checkout@v2

      - name: Setup
        run: |
          npm ci
          npm run test
          cd ./frontend
          npm ci
          cd ..
          echo "Deploying to Prod..."
          npx sst deploy --stage prod

