name: Deployment Pipeline
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::952488780586:role/github-deploy-to-cloudformation-role
          aws-region: us-east-1
      - uses: actions/checkout@v2 # Fetch repository.
      - name: Setup
        id: setup
        run: |
          npm ci
          npm run test
          cd ./frontend
          npm ci
          cd ..
          echo "Deploying to dev..."
          npx sst deploy --stage dev-${{ github.head_ref }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::738219726652:role/github-deploy-to-cloudformation-role
          aws-region: us-east-1
      - uses: actions/checkout@v2 # Fetch repository.
      # TODO: Delete branch deployment when merged to master. I left some console logs to test if we can easily get branch name
      - name: Setup
        id: setup
        run: |
          npm ci
          npm run test
          cd ./frontend
          npm ci
          cd ..
          echo "Deploying to Prod..."
          npx sst deploy --stage prod
          
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}

          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo $branch

          ${{ github.event.base_ref }}

